# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      CONDA_DEPENDENCIES: "menuinst console_shortcut"
      PIP_DEPENDENCIES: "https://github.com/conda/constructor/archive/master.zip awscli"

  matrix:
      - TARGET_ARCH: x86
        PYTHON_VERSION: "3.6"
      - TARGET_ARCH: x64
        PYTHON_VERSION: "3.6"

matrix:
    fast_finish: true

platform:
    -x64

install:

    # Install Miniconda
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% constructor ."
  
